const fileData= 
  {
      name:"src",
      isFolder:true,
      child:[
         {
            name:"assets",
            isFolder:true,
            child:[
               {
                  name:"images.js",
                  isFolder:false,
                  child:[]
               },
               {
                  name:"videos.mp4",
                  isFolder:false,
                  child:[]
               },
               {
                  name:"logo.svg",
                  isFolder:false,
                  child:[]
               }
            ] 
         },
         {
            name:"components",
            isFolder:true,
            child:[
               {
                  name:"buttons",
                  isFolder:true,
                  child:[
                     {
                        name:"Insert.jsx",
                        isFolder:false,
                        child:[]
                     },
                     {
                        name:"Update.jsx",
                        isFolder:false,
                        child:[]
                     },
                     {
                        name:"Delete.jsx",
                        isFolder:false,
                        child:[]
                     },
                     {
                        name:"Read.jsx",
                        isFolder:false,
                        child:[]
                     }
                  ]
               },
               {
                  name:"Home.jsx",
                  isFolder:false,
                  child:[]
               },
               {
                  name:"Header.jsx",
                  isFolder:false,
                  child:[]
               },
               {
                  name:"Footer.jsx",
                  isFolder:false,
                  child:[]
               },
               {
                  name:"Body,jsx",
                  isFolder:false,
                  child:[]
               }
            ] 
         }
      ]
   }




export default fileData; 